I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 279, in script
    python:
  File "renpy/common/00start.rpy", line 279, in script
    python:
  File "renpy/common/00start.rpy", line 283, in <module>
    renpy.call_in_new_context("_main_menu")
  File "renpy/common/00action_file.rpy", line 499, in __call__
    renpy.load(fn)
Exception: Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\main.py", line 652, in main
    run(restart)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\main.py", line 148, in run
    renpy.execution.run_context(True)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\execution.py", line 958, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 279, in script
    python:
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "renpy/common/00start.rpy", line 279, in script
    python:
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 283, in <module>
    renpy.call_in_new_context("_main_menu")
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\game.py", line 377, in call_in_new_context
    return renpy.execution.run_context(False)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\execution.py", line 958, in run_context
    context.run()
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
    python hide:
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
    python hide:
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in <module>
    python hide:
  File "renpy/common/_layout/screen_main_menu.rpym", line 35, in _execute_python_hide
    ui.interact()
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\display\core.py", line 2215, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\display\core.py", line 3278, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\display\layout.py", line 1294, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\display\transition.py", line 53, in event
    return self.new_widget.event(ev, x, y, st) # E1101
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\display\layout.py", line 1294, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\display\layout.py", line 1294, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\display\screen.py", line 793, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\display\layout.py", line 1294, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\display\layout.py", line 1523, in event
    rv = super(Window, self).event(ev, x, y, st)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\display\layout.py", line 288, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\display\layout.py", line 1294, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\display\layout.py", line 1523, in event
    rv = super(Window, self).event(ev, x, y, st)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\display\layout.py", line 288, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\display\layout.py", line 1294, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\display\layout.py", line 288, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\display\behavior.py", line 1180, in event
    return handle_click(self.clicked)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\display\behavior.py", line 1101, in handle_click
    rv = run(action)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\display\behavior.py", line 401, in run
    return action(*args, **kwargs)
  File "renpy/common/00action_file.rpy", line 499, in __call__
    renpy.load(fn)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\loadsave.py", line 826, in load
    log.unfreeze(roots, label="_after_load")
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\rollback.py", line 1135, in unfreeze
    self.rollback(0, force=True, label=label, greedy=greedy, on_load=True)
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\rollback.py", line 930, in rollback
    self.load_failed()
  File "C:\Users\Administrator\Documents\Arches-1.0-win\renpy\rollback.py", line 848, in load_failed
    raise Exception("Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?")
Exception: Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090902
Arches 1.0
Fri Mar 28 00:22:16 2025
